"""
Django settings for recsys project.

Generated by 'django-admin startproject' using Django 3.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""
import os
from pathlib import Path

from .settings import *

DEBUG = False

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'rms',
        'USER': 'cacti',
        'PASSWORD': 'Cacti_12345',
        'HOST': '192.168.0.49',
        'PORT': '5432',
        "CHARSET": "utf-8",
    }
}

RQ_QUEUES = {
    'default': {
        'HOST': '192.168.0.51',
        'PORT': 6379,
        'DB': 0,
        'PASSWORD': "UEWA21CzY3Gwclf5pTXPdpsEUehFFiNQF+tl6NwADl4=",
        'DEFAULT_TIMEOUT': 360,
        'ASYNC': True,
    },
}

# Custom App config
RECOMMEND_REDIS = [
    {"host": "192.168.0.51", "port": "6379", "ssl": False, "password": "UEWA21CzY3Gwclf5pTXPdpsEUehFFiNQF+tl6NwADl4="},
]

API_V2_HOSTS = [
    "https://apiv2.aminersz.cn",
]
RECALL_DATA_URL = "http://192.168.0.53/aminer"


REPORT_RECEIVERS = [
    "peng.zhang@aminer.cn",
    "xiaotao.peng@aminer.cn",
    "meiling.huang@aminer.cn",
    "yifan.zhu@aminer.cn",
    "huihui.yuan@aminer.cn",
]

SPACY_WORD_LIB = "en_core_web_lg"

MONGO = {
    "aminer_reader": {
        'host': "192.168.0.204",
        'port': 27017,
        'authSource': "aminer",
        'user': "aminer_platform_reader",
        'password': "Reader@123",
    },
    "aminer": [
        {
            'host': "192.168.0.204",
            'port': 27017,
            'authSource': "admin",
            'user': "aminer_pengxiaotao",
            'password': "UEWA21CzY3Gwclf5pTXPdpsEUehFFiNQF",
        },
        {
            'host': "192.168.0.204",
            'port': 27017,
            'authSource': "admin",
            'user': "aminer_pengxiaotao",
            'password': "UEWA21CzY3Gwclf5pTXPdpsEUehFFiNQF",
        },
        {
            'host': "192.168.0.204",
            'port': 27017,
            'authSource': "admin",
            'user': "aminer_pengxiaotao",
            'password': "UEWA21CzY3Gwclf5pTXPdpsEUehFFiNQF",
        },
    ]
}

PERF_COLLECT_OUTPUT = "/data/weblog/perf.csv"

DATA_API_HOST = "https://datacenter.aminer.cn/gateway"  # public host
'''
SSDB = {
    "host": "192.168.0.212",
    "port": 8888,
}
'''
SSDB = {
    "host": None,
    "port": None,
}

MEILI_SEARCH = "http://192.168.0.52:7700"
TOPIC_EMBEDDING_URL = "http://192.168.0.53:6091/get_topic_embedding"
MILVUS_HOST = "192.168.0.50"
MILVUS_PORT = "19530"

#GPU_HOST = "192.168.0.51"
GPU_HOST = "221.194.152.90"
GPU_PORT = 23966
GPU_USER = "aminer"
#GPU_HOME = "/data/cache/aminer"
GPU_HOME = "/vepfs/data/cache/aminer"
GPU_HTTP_HOST = "172.24.14.110"
GPU_HTTP_PORT = 80
GPU_NON_KEYWORD_RESULT_URL = f"http://{GPU_HTTP_HOST}:{GPU_HTTP_PORT}/aminer/output_recommendation"
GPU_USER_EVENT_LOG_URL = f"http://{GPU_HTTP_HOST}:{GPU_HTTP_PORT}/aminer/"

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'filters': {
        'require_debug_false': {
            '()': 'django.utils.log.RequireDebugFalse'
        }
    },
    'formatters': {
        'verbose': {
            'format': '%(levelname)s %(asctime)s %(filename)s:%(funcName)s:%(lineno)d:: %(message)s'
        },
        'simple': {
            'format': '%(levelname)s %(message)s'
        },
    },
    'handlers': {
        'console': {
            'level': 'DEBUG',
            'class': 'logging.StreamHandler',
            'formatter': 'simple'
        },
        'mail_admins': {
            'level': 'ERROR',
            'filters': ['require_debug_false'],
            'class': 'django.utils.log.AdminEmailHandler',
            'include_html': True,
        },
        'file': {
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': "/data/weblog/rms.debug.log",
            'level': 'DEBUG',
            'formatter': 'verbose',
            'backupCount': 1,
            'maxBytes': 1024*1024*100,
        },
    },
    'loggers': {
        '': {
            'handlers': ['file', "mail_admins"],
            'level': 'WARNING',
            #'level': 'INFO',
            'propagate': True,
        },
        "rq.worker": {
            "handlers": ["file", "mail_admins"],
            "level": "WARNING"
        },
    }
}
