"""
Django settings for recsys project.

Generated by 'django-admin startproject' using Django 3.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

from .settings import *

# Custom App config
RECOMMEND_REDIS = [
    # {"host": "localhost", "port": "6379", "ssl": False, 'password': None},
    # {"host": "10.10.0.28", "port": "6379", "ssl": False, "password": "UEWA201CzY3Gwclf5pTXPdpsEUehFFiNQF+tl6NwADl4="},
    {"host": "10.10.0.38", "port": "6379", "ssl": False, "password": "UEWA21CzY3Gwclf5pTXPdpsEUehFFiNQF+tl6NwADl4="}, # prod

]

RQ_QUEUES = {
    'default': {
        'HOST': 'localhost',
        'PORT': 6379,
        'DB': 1,
        'PASSWORD': None,
        'DEFAULT_TIMEOUT': 360,
        'ASYNC': True,
    },
}

# Celery Configuration Options
#CELERY_TIMEZONE = "Australia/Tasmania"
CELERY_TASK_TRACK_STARTED = True
CELERY_TASK_TIME_LIMIT = 3600
CELERY_BROKER_URL = "redis://localhost:6379/0"
CELERY_RESULT_BACKEND = "redis://localhost:6379/1"
IMPORTS = ('recsys.background')

REPORT_RECEIVERS = [
    "xiaotao.peng@aminer.cn"
]

SPACY_WORD_LIB = "en_core_web_sm"

LOCAL_CACHE_HOME = "/Users/pengxiaotao/Documents/cache"

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': 'db.sqlite3',
#         "OPTIONS": {
#             "timeout": 20,
#         }
#     }
# }

# prod
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'rms',
        'USER': 'cacti',
        'PASSWORD': 'Cacti_12345',
        'HOST': '10.10.0.39',
        'PORT': '5432',
        "CHARSET": "utf-8",
    }
}


MONGO = {
    "aminer_reader": {
        'host': "192.168.6.208",
        'port': 37017,
        'authSource': "aminer",
        'user': "aminer_platform_reader",
        'password': "Reader@123",
    },
    "aminer": [
        {
            'host': "10.10.0.10",
            'port': 27017,
            'authSource': "admin",
            'user': "aminer_pengxiaotao",
            'password': "UEWA21CzY3Gwclf5pTXPdpsEUehFFiNQF",
        },
        {
            'host': "10.10.0.8",
            'port': 27017,
            'authSource': "admin",
            'user': "aminer_pengxiaotao",
            'password': "UEWA21CzY3Gwclf5pTXPdpsEUehFFiNQF",
        },
        {
            'host': "10.10.0.9",
            'port': 27017,
            'authSource': "admin",
            'user': "aminer_pengxiaotao",
            'password': "UEWA21CzY3Gwclf5pTXPdpsEUehFFiNQF",
        },
    ]
}


LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'filters': {
        'require_debug_false': {
            '()': 'django.utils.log.RequireDebugFalse'
        }
    },
    'formatters': {
        'verbose': {
            'format': '%(levelname)s %(asctime)s %(filename)s.%(funcName)s.%(lineno)d: %(message)s'
        },
        'simple': {
            'format': '%(levelname)s %(message)s'
        },
    },
    'handlers': {
        'console': {
            'level': 'DEBUG',
            'class': 'logging.StreamHandler',
            'formatter': 'simple'
        },
        'mail_admins': {
            'level': 'ERROR',
            'filters': ['require_debug_false'],
            'class': 'django.utils.log.AdminEmailHandler',
            'include_html': True,
        },
        'file': {
            'class': 'logging.FileHandler',
            'filename': os.path.join(BASE_DIR, "debug.log"),
            'level': 'INFO',
            'formatter': 'verbose',
        },
    },
    'loggers': {
        '': {
            'handlers': ['file'],
            'level': 'INFO',
            'propagate': True,
        },
        'recsys.*': {
            'handlers': ['file'],
            'level': 'INFO',
            'propagate': True,
        },
    }
}

LOCAL_CACHE_HOME = "/Users/pengxiaotao/Documents/cache"
if not os.path.exists(LOCAL_CACHE_HOME):
    os.makedirs(LOCAL_CACHE_HOME)
