# Generated by Django 3.2.5 on 2021-08-27 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recsys', '0002_actionlog_author_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actionlog',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
