# Generated by Django 3.2.5 on 2021-09-15 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recsys', '0004_actionlog_abflag'),
    ]

    operations = [
        migrations.AddField(
            model_name='actionlog',
            name='type',
            field=models.SmallIntegerField(default=1),
            preserve_default=False,
        ),
    ]
