# Generated by Django 3.2.5 on 2021-11-05 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recsys', '0006_alter_actionlog_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='actionlog',
            name='fmail',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='actionlog',
            name='ftype',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='actionlog',
            name='fuser',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
