# Generated by Django 3.2.5 on 2021-12-01 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recsys', '0008_auto_20211129_1448'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actionlog',
            name='up',
        ),
        migrations.AddField(
            model_name='actionlog',
            name='ls',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
