# Generated by Django 3.2 on 2021-12-09 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recsys', '0009_auto_20211201_1626'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessLogSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_created=True)),
                ('happen_time', models.DateTimeField(unique=True)),
                ('business', models.CharField(max_length=16)),
                ('total', models.IntegerField()),
                ('status_200_number', models.IntegerField()),
                ('status_5xx_number', models.IntegerField()),
                ('resp_body_bytes_sum', models.PositiveBigIntegerField()),
                ('resp_seconds_sum', models.FloatField()),
            ],
        ),
    ]
