# Generated by Django 3.2 on 2021-12-09 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recsys', '0010_accesslogsnapshot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesslogsnapshot',
            name='create_at',
            field=models.DateTimeField(auto_created=True, auto_now_add=True),
        ),
    ]
