# Generated by Django 3.2 on 2021-12-09 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recsys', '0011_alter_accesslogsnapshot_create_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesslogsnapshot',
            name='happen_time',
            field=models.DateTimeField(),
        ),
    ]
