# Generated by Django 3.2.5 on 2022-04-13 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recsys', '0012_alter_accesslogsnapshot_happen_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='HotPaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_created=True)),
                ('pub_id', models.CharField(max_length=32)),
                ('modify_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='accesslogsnapshot',
            name='resp_body_bytes_sum',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='accesslogsnapshot',
            name='resp_seconds_sum',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='accesslogsnapshot',
            name='status_200_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='accesslogsnapshot',
            name='status_5xx_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='accesslogsnapshot',
            name='total',
            field=models.IntegerField(default=0),
        ),
    ]
