# Generated by Django 3.2.5 on 2022-04-13 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recsys', '0013_auto_20220413_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotpaper',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
