# Generated by Django 3.2.5 on 2022-04-28 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recsys', '0017_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='ad_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ad',
            name='ad_type',
            field=models.CharField(blank=True, choices=[('ad_human', 'ad_human'), ('ad_ai2000', 'ad_ai2000')], max_length=255, null=True),
        ),
    ]
