# Generated by Django 3.2.5 on 2022-05-05 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recsys', '0018_auto_20220428_1715'),
    ]

    operations = [
        migrations.AddField(
            model_name='actionlog',
            name='recall_type',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
