# Generated by Django 3.2.5 on 2022-05-10 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recsys', '0020_highqualitypaper'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotpaper',
            name='interpret',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hotpaper',
            name='interpret_author',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
