# Generated by Django 3.2.5 on 2022-05-11 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recsys', '0021_auto_20220510_1108'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotpaper',
            name='report_id',
            field=models.CharField(blank=True, max_length=24, null=True),
        ),
    ]
