# Generated by Django 3.2.5 on 2022-05-16 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recsys', '0023_auto_20220513_1143'),
    ]

    operations = [
        migrations.AddField(
            model_name='highqualitypaper',
            name='subject_en',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='highqualitypaper',
            name='subject_zh',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
