# Generated by Django 3.2.5 on 2022-06-05 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recsys', '0024_auto_20220516_1057'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actionlog',
            name='fmail',
        ),
        migrations.RemoveField(
            model_name='actionlog',
            name='ftype',
        ),
        migrations.RemoveField(
            model_name='actionlog',
            name='fuser',
        ),
    ]
