# Generated by Django 3.2.5 on 2022-08-08 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recsys', '0025_auto_20220605_1309'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserEventLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user', models.CharField(blank=True, max_length=64, null=True)),
                ('tc', models.DateTimeField()),
                ('tc_day', models.DateField()),
                ('type', models.CharField(blank=True, max_length=32, null=True)),
                ('query', models.CharField(blank=True, max_length=255, null=True)),
                ('uid', models.CharField(blank=True, max_length=64, null=True)),
                ('ud', models.CharField(blank=True, max_length=64, null=True)),
                ('item', models.CharField(blank=True, max_length=32, null=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='ad',
            name='ad_type',
            field=models.CharField(blank=True, choices=[('ai2k', 'ai2k')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='highqualitypaper',
            name='abstract',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='highqualitypaper',
            name='ts',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
