# Generated by Django 3.2.5 on 2022-08-10 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recsys', '0026_auto_20220808_1503'),
    ]

    operations = [
        migrations.AddField(
            model_name='highqualitypaper',
            name='category',
            field=models.TextField(blank=True, null=True),
        ),
    ]
