# Generated by Django 3.2.5 on 2022-11-02 03:13

from django.db import migrations, models
import recsys.models


class Migration(migrations.Migration):

    dependencies = [
        ('recsys', '0028_auto_20220919_1751'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotpaper',
            name='is_top',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hotpaper',
            name='top_end_at',
            field=models.DateTimeField(blank=True, help_text='置顶结束时间', null=True),
        ),
        migrations.AddField(
            model_name='hotpaper',
            name='top_start_at',
            field=models.DateTimeField(blank=True, help_text='置顶开始时间', null=True),
        ),
        migrations.AlterField(
            model_name='hotpaper',
            name='pub_id',
            field=models.CharField(max_length=32, validators=[recsys.models.validate_paper_id]),
        ),
    ]
