# Generated by Django 3.2.5 on 2022-11-02 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recsys', '0029_auto_20221102_1113'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotpaper',
            name='top_reason_en',
            field=models.CharField(blank=True, help_text='英文置顶理由', max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='hotpaper',
            name='top_reason_zh',
            field=models.CharField(blank=True, help_text='中文置顶理由', max_length=250, null=True),
        ),
    ]
