# Generated by Django 3.2.5 on 2022-11-17 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recsys', '0030_auto_20221102_1911'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotpaper',
            name='display_device',
            field=models.CharField(blank=True, choices=[('PC', 'pc'), ('mini_program', 'mini_program')], help_text='展示终端', max_length=32, null=True),
        ),
    ]
