# Generated by Django 3.2.5 on 2022-12-06 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recsys', '0031_hotpaper_display_device'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotpaper',
            name='video_url',
            field=models.TextField(blank=True, help_text='视频链接', null=True),
        ),
    ]
