# Generated by Django 3.2.5 on 2022-12-07 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recsys', '0032_hotpaper_video_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotpaper',
            name='pub_topic_id',
            field=models.CharField(blank=True, help_text='必读论文ID', max_length=32, null=True),
        ),
    ]
