# Generated by Django 3.2.5 on 2023-01-04 08:49

from django.db import migrations, models
import recsys.models


class Migration(migrations.Migration):

    dependencies = [
        ('recsys', '0033_hotpaper_pub_topic_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotpaper',
            name='ai2k_authors',
            field=models.TextField(blank=True, help_text="一行一个作者，每行用'|｜'分开。示例：学者中文名||学者英文名||机构||学者ID", null=True, validators=[recsys.models.validate_ai2k_authors]),
        ),
        migrations.AddField(
            model_name='hotpaper',
            name='ai2k_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hotpaper',
            name='ai2k_keywords',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='hotpaper',
            name='ai2k_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='hotpaper',
            name='category',
            field=models.CharField(choices=[('Pub', 'pub'), ('Topic', 'topic'), ('AI2k', 'ai2k')], default="pub", max_length=32),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hotpaper',
            name='pub_id',
            field=models.CharField(blank=True, max_length=32, null=True, validators=[recsys.models.validate_paper_id]),
        ),
    ]
