# Generated by Django 3.2.5 on 2023-01-05 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recsys', '0034_auto_20230104_1649'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotpaper',
            name='ai2k_id',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
