# Generated by Django 3.2.5 on 2023-02-06 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recsys', '0035_hotpaper_ai2k_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='actionlog',
            name='query',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='hotpaper',
            name='category',
            field=models.CharField(choices=[('pub', 'Pub'), ('topic', 'Topic'), ('ai2k', 'AI2000')], max_length=32),
        ),
    ]
