# Generated by Django 4.2 on 2023-05-16 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recsys', '0038_uservector'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatRound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(db_index=True, max_length=128)),
                ('user_message', models.TextField()),
                ('user_pubs', models.JSONField()),
                ('assistant_message', models.TextField()),
                ('create_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['create_at'],
            },
        ),
    ]
