# Generated by Django 4.2 on 2023-05-24 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recsys', '0039_chatround'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatround',
            name='assistant_extend_message',
            field=models.TextField(default=None, blank=True, null=True),
            preserve_default=False,
        ),
    ]
